from utils import colors


# Segments colors.
USERATHOST_BG = colors.SMERALD
USERATHOST_FG = colors.WHITE

SSH_BG = colors.LIGHT_ORANGE
SSH_FG = colors.WHITE

CURRENTDIR_BG = colors.DARK_GREY
CURRENTDIR_FG = colors.LIGHT_GREY

READONLY_BG = colors.LIGHT_GREY
READONLY_FG = colors.RED

EXITCODE_BG = colors.RED
EXITCODE_FG = colors.WHITE

PADDING_BG = colors.BLACK

GIT_UNTRACKED_FILES_BG = colors.PINKISH_RED
GIT_UNTRACKED_FILES_FG = colors.NEARLY_WHITE_GREY
GIT_CHANGES_NOT_STAGED_BG = colors.PINKISH_RED
GIT_CHANGES_NOT_STAGED_FG = colors.NEARLY_WHITE_GREY
GIT_ALL_CHANGES_STAGED_BG = colors.LIGHT_ORANGE
GIT_ALL_CHANGES_STAGED_FG = colors.DARKER_GREY
GIT_CLEAN_BG = colors.PISTACHIO
GIT_CLEAN_FG = colors.DARKER_GREY

GITREPO_BG = colors.DARK_PURPLE
GITREPO_FG = colors.WHITE

VENV_BG = colors.SMERALD
VENV_FG = colors.EXTRA_LIGHT_GREY

JOBS_BG = colors.DARK_PURPLE
JOBS_FG = colors.WHITE

TIME_BG = colors.DARKER_GREY
TIME_FG = colors.MID_DARK_GREY

USER_BG = colors.WHITE
USER_FG = colors.SMERALD

HOST_BG = colors.SMERALD
HOST_FG = colors.WHITE

ARD_BG = colors.SMERALD
ARD_FG = colors.EXTRA_LIGHT_GREY

ARDTIMER_BG = colors.EXTRA_LIGHT_GREY
ARDTIMER_FG = colors.SMERALD

KUBE_BG = colors.SMERALD
KUBE_FG = colors.EXTRA_LIGHT_GREY
