from utils import colors


# Segments colors.
USERATHOST_BG = colors.MID_GREY
USERATHOST_FG = colors.WHITE

USER_BG = colors.LIGHTER_GOLD
USER_FG = colors.DARK_GREY

HOST_BG = colors.RED_2
HOST_FG = colors.MID_ORANGE_2

SSH_BG = colors.LIGHT_ORANGE
SSH_FG = colors.WHITE

CURRENTDIR_BG = colors.DARK_GREY
CURRENTDIR_FG = colors.LIGHT_GREY

READONLY_BG = colors.LIGHT_GREY
READONLY_FG = colors.RED

EXITCODE_BG = colors.RED
EXITCODE_FG = colors.WHITE

PADDING_BG = colors.BLACK

GIT_UNTRACKED_FILES_BG = colors.RED
GIT_UNTRACKED_FILES_FG = colors.MID_ORANGE_2
GIT_CHANGES_NOT_STAGED_BG = colors.PINKISH_RED
GIT_CHANGES_NOT_STAGED_FG = colors.NEARLY_WHITE_GREY
GIT_ALL_CHANGES_STAGED_BG = colors.LIGHT_ORANGE
GIT_ALL_CHANGES_STAGED_FG = colors.DARKER_GREY
GIT_CLEAN_BG = colors.DARKER_GREY
GIT_CLEAN_FG = colors.MID_GREY

VENV_BG = colors.SMERALD
VENV_FG = colors.EXTRA_LIGHT_GREY

JOBS_BG = colors.DARK_PURPLE
JOBS_FG = colors.WHITE

TIME_BG = colors.BLACK
TIME_FG = colors.MID_DARK_GREY
